name: CD - Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: deploy
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            set -e

            echo "=== Move to project directory ==="
            cd /home/deploy/enterprise_devsecops_lab

            echo "=== Pull latest code ==="
            git pull origin main

            echo "=== Ensure env file exists ==="
            if [ ! -f app/.env ]; then
              cat <<EOF > app/.env
  POSTGRES_DB=labdb
  POSTGRES_USER=labuser
  POSTGRES_PASSWORD=labpass
  POSTGRES_HOST=db
  POSTGRES_PORT=5432
  EOF
            fi

            echo "=== Deploy containers ==="
            docker compose -f docker/docker-compose.yml down
            docker compose -f docker/docker-compose.yml up -d --build
