name: CI - Build & Scan Container

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          # Build Docker image with correct Dockerfile path
          docker build -t enterprise-devsecops:latest -f docker/Dockerfile .


## TRIVY SCAN ##


  trivy-scan:
    name: Trivy Container Scan
    runs-on: ubuntu-latest
    needs: build  # runs after build job

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build Docker image (again, in this job)
        run: |
          docker build -t enterprise-devsecops:latest -f docker/Dockerfile .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: enterprise-devsecops:latest
          severity: HIGH,CRITICAL
          exit-code: 1
          ignore-unfixed: true
